# Generated by Django 5.1.1 on 2025-05-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
    ]
