# Generated by Django 5.1.1 on 2025-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_trigger_render_redeploy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
