# Generated by Django 5.1.1 on 2025-03-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publishDate',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
