# Generated by Django 5.1.1 on 2025-06-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
