# Generated by Django 5.1.1 on 2025-03-02 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_createdat_book_created_at_and_more'),
        ('bookshelf', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookshelf.bookshelf'),
        ),
    ]
