# Generated by Django 5.1.1 on 2025-03-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
